### ISSUE TITLE
Morning session: peer-to-peer code reviews

### ISSUE THREAD

**Issue by BahirHakimy** [shayan1234554321/To-do#4]
# Your code looks great, however, there are some suggestions that will make your code even better 💯 
## Suggestions
-  Generally speaking, I think it was an interesting implementation but I think the entire code can still be optimized and reduced. As I said, it will be nice if you can base your implementation on your awesome books library class.
- The naming conventions for functions don't follow a consistent style, It would be nice if you follow a consistent naming convention which will make your codebase tidy.
- Great work on implementing local storage functions, however, I think it would be better if you use `localStorage.setItem(key,value)` cause it's cleaner and easier to understand. https://github.com/shayan1234554321/To-do/blob/03614fb81df0f1b91c3726e3195ccc2411bbe6c2/src/local-storage.js#L1-L6
- Also the approach for rendering tasks is great, however, it would be shorter and faster if you first sort your array in every **CRUD** operation and use `Array.map()` to render the tasks.  https://github.com/shayan1234554321/To-do/blob/03614fb81df0f1b91c3726e3195ccc2411bbe6c2/src/index.js#L17-L23
- You can also keep your CSS code dry if you apply common rules to top most elements *Kajal*

### Cheers and happy coding 🍻

**Comment by shayan1234554321** [comment]
Thanks for that great suggestion. Will implement them 🤯
